name: Install and Run APK

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Emulator and Install APK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: arm64-v8a
          target: google_apis
          profile: Nexus 6
          script: |
            # دانلود APK
            curl -L -o app.apk "https://github.com/forgotenmywin/Khoshtib/releases/download/jjljkjl/instagram-441-0-0-0-72.apk" --fail --retry 3
            
            # نصب
            adb install app.apk
            
            # اجرا
            adb shell am start -n com.instagram.android/com.instagram.mainactivity.LauncherActivity
